# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tFQ_8Fw1sk2OXNrctFixA3YCbC9uwY1e
"""

import math

def calculate_circle_properties(radius):
    # 計算圓周長
    circumference = 2 * math.pi * radius
    # 計算圓面積
    area = math.pi * radius ** 2

    return circumference, area

# 輸入半徑
radius_input = float(input("請輸入圓的半徑："))

# 計算圓周長和圓面積
circumference_result, area_result = calculate_circle_properties(radius_input)

print(f"圓周長：{circumference_result:.2f}")
print(f"圓面積：{area_result:.2f}")

def collect_user_data():
    # 收集用戶輸入的資料
    name = input("請輸入您的姓名：")
    age = int(input("請輸入您的年齡："))
    height = float(input("請輸入您的身高（米）："))
    favorite_color = input("請輸入您喜愛的顏色：")

    # 將資料存儲在字典中
    user_data = {
        "姓名": name,
        "年齡": age,
        "身高": height,
        "喜愛的顏色": favorite_color
    }

    return user_data

def generate_summary(user_data):
    # 根據收集到的資料生成摘要
    summary = f"{user_data['姓名']}, {user_data['年齡']}歲, 身高{user_data['身高']}米, 喜愛的顏色是{user_data['喜愛的顏色']}。"
    return summary

if __name__ == "__main__":
    user_data = collect_user_data()
    summary = generate_summary(user_data)
    print("個人資料摘要：")
    print(summary)

def main():
    try:
        user_input = int(input("請輸入一個整數："))
        if user_input % 2 == 0:
            print(f"{user_input} 是一個偶數。")
        else:
            print(f"{user_input} 不是一個偶數。")
    except ValueError:
        print("請輸入有效的整數。")

if __name__ == "__main__":
    main()